### ISSUE TITLE
Use todonotes library instead of user command

### ISSUE THREAD

**Issue by MatejZidek** [johnhw/l4template#2]
https://github.com/johnhw/l4template/blob/f9755f4a481b2814fa1fd5473e52b0b104cd0592/l4proj.cls#L311

There is widely used `todonotes` library: https://ctan.org/pkg/todonotes. The `\todo` notes can be on the side of the text, there are also handy commands `\listoftodos` and `\missingfigure`.

All the todos can be easily disabled (for better page limit tracking, prepublishing or if there's not enough time to finish all of them...) with adding `[disabled]` as an option to the package without the need to remove them (or comment out, which makes them forgotten forever as well). Hence it would be great to have`\usepackage{todonotes}` in the main file (l4proj.tex), to be able to add the `[disabled]` option without modifying the class definition.

Current user defined command `\todo` in the above line conflicts with using this library.

**Comment by johnhw** [comment]
Thanks Matej, I will update this for next year -- I don't want to change the format at the very last minute for everyone. You are free to make this change yourself in your own submission.
